[tool.poetry]
name = "joblib-toy"
version = "0.1.0"
description = ""
authors = ["mehedee-hassan <razin.meha@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
joblib = "^1.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
